<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 * Description of create-recipe
 *
 * @author Alexandra Jäger <alexandra.jaeger@student.uibk.ac.at>
 */

 $title = 'Create new recipe';
 $this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('recipe', array('action' => 'createRecipe')));
 $form->prepare();

 echo "<br>";
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('recipeName'));
 echo "<br>";
 echo $this->formCollection($form->get('ingredient'));
 echo $this->formRow($form->get('ingredientAmount'));
 echo $this->formCollection($form->get('weightUnit'));
 echo "<br>";
 echo $this->formRow($form->get('instructions'));
 echo "<br>";
 echo $this->formRow($form->get('duration'));
 echo "<br>";
 echo $this->formCollection($form->get('difficultyID'));
 echo "<br>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
