<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 * Description of create-recipe
 *
 * @author Alexandra Jäger <alexandra.jaeger@student.uibk.ac.at>
 */

 $title = 'Create new recipe';
 $this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('recipe', array('action' => 'createRecipe')));
 $form->prepare();

 echo "<br>";
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('recipeName'));
 echo "<br>";
 echo $this->formCollection($form->get('ingredients'));
 echo "<br>";
 ?>
 <button onclick="return addIngredientFieldset()">I need more ingredients!</button>
 <br>
 <br>
 <script>
     function addIngredientFieldset() {
         var currentCount = $('form > fieldset > fieldset').length;
         var template = $('form > fieldset > span').data('template');
         template = template.replace(/__ingredientGroup__/g, currentCount);
         //$('form > fieldset > fieldset')
         $("#ingredientGroupFieldset").append(template);

         return false;
     }
 </script>
 
 <?php
 echo $this->formRow($form->get('instructions'));
 echo "<br>";
 echo $this->formRow($form->get('duration'));
 echo "<br>";
 echo $this->formCollection($form->get('difficultyID'));
 echo "<br>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
