<?php

 $title = $recipe->recipeName;
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <?php
  if (strcmp($recipe->description, "") != 0) {
     echo "<br>";
     echo "<h4>Short Description:</h4>";
     echo "<br>";
     echo $recipe->description;
     echo "<br>";
     echo "<br>";
 }
 ?>
 
 <h4>Ingredients:</h4>
 <br>
<table class="table">
 <tr>
     <th>Ingredient</th>
     <th>Amount</th>
     <th>Weight Unit</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($ingredientsOfRecipe as $ingredient) : ?>
    <tr>
         <td><?php echo $this->escapeHtml($ingredientNames[$ingredient->ingredientID]);?></td>
         <td><?php echo $this->escapeHtml($ingredient->amount);?></td>
         <td><?php echo $this->escapeHtml($weightUnits[$ingredient->weightUnitID]);?></td>
     </tr>
 <?php endforeach; ?>
 </table>
 
      
 <h4>Instructions:</h4>
 <br>
 <?php echo $recipe->instructions; ?>
 <br>
 <br>
 
 <h4>Difficulty:</h4>
 <?php echo $difficulty; ?>
 
 <h4>Duration:</h4>
 <?php echo $recipe->duration . " minutes"; ?>