<?php

 $title = $recipe->recipeName;
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <?php
  if (strcmp($recipe->description, "") != 0) {
     echo "<br>";
     echo "<h4>Short Description:</h4>";
     echo "<br>";
     echo $recipe->description;
     echo "<br>";
     echo "<br>";
 }
 ?>
 
 <h4>Ingredients:</h4>
 <br>
<table class="table">
 <tr>
     <th>Ingredient</th>
     <th>Amount</th>
     <th>Weight Unit</th>
     <th>&nbsp;</th>
 </tr>
 <?php 
 $myIngredient="";
 foreach ($ingredientsOfRecipe as $ingredient) : ?>
    <tr>
         <td><?php echo $this->escapeHtml($ingredientNames[$ingredient->ingredientID]);?></td>
         <td><?php echo $this->escapeHtml($ingredient->amount);?></td>
         <td><?php echo $this->escapeHtml($weightUnits[$ingredient->weightUnitID]);?></td>
        
     </tr>
 <?php 
         $myIngredient .= "\r\n".$ingredientNames[$ingredient->ingredientID] . "\t" . $ingredient->amount ."". $ingredient->weightUnitID;
      endforeach; ?>
 </table>
 
      
 <h4>Instructions:</h4>
 <br>
 <?php echo $recipe->instructions; ?>
 <br>
 <br>
 
 <h4>Difficulty:</h4>
 <?php echo $difficulty; ?>
 
 <h4>Duration:</h4>
 <?php echo $recipe->duration . " minutes"; ?>

 <span style="position: absolute;right: 110px;">
    <form action="" method="POST">
        <input type="submit" name="download" Value="Download">
    </form>
 </span>
 
 <?php
 
if(@$_POST['download']){ 
    $file ="recipe.txt";
    $handle = fopen($file, "w");
    $contents=$recipe->recipeName . "\r\n".
              "\r\nShort Description:" . 
              "\r\n".$recipe->description . "\r\n".
              "\r\nIngredient:" . 
              $myIngredient . "\r\n".
              "\r\nInstructions:" . 
              "\r\n".$recipe->instructions . "\r\n".
              "\r\nDifficulty: " .$difficulty . "\r\n".
              "\r\nDuration: " .$recipe->duration . " minutes";
    
    fwrite($handle, $contents);
    fclose($handle);
    if(file_exists($file)) {
            header('Content-Description: File Transfer');
            header('Content-Type: application/octet-stream');
            header('Content-Disposition: attachment; filename='.basename($file));
            header('Content-Transfer-Encoding: binary');
            header('Expires: 0');
            header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
            header('Pragma: public');
            header('Content-Length: ' . filesize($file));
            ob_clean();
            flush();
            readfile($file);
            exit;
     }
}