<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Latest recipes';
 $this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <?php echo $this->navigation()->breadcrumbs()->render(); ?>
     
     <!--CVL5 for all user-->                    
      <?php echo "<a href=".$this->url('search', array('action'=>'search' )).">Search for recipes</a>&nbsp;&nbsp;";
      ?>      
         
     <?php
     if(strcmp($_SESSION['user'],"") != 0) {
        echo "<a href=".$this->url('recipe', array('action'=>'createRecipe')).">Add new recipe</a>&nbsp;&nbsp;";
         //CVL3 ins        
        echo "<a href=".$this->url('list', array('action'=>'viewList')).">View favorite recipes</a>";
            
        if(@$_POST['showMyOwnRecipes']){
        ?>    
            <form action="" method="POST" style="position: absolute;right: 120px;">
                  <input type="submit" name="showMyAllRecipes" Value="Show all recipes" style="background-color: transparent;color: blue;border: none;">
            </form>
        <?php }
        else{ ?>
            <form action="" method="POST" style="position: absolute;right: 120px;">
                  <input type="submit" name="showMyOwnRecipes" Value="Show my own recipes" style="background-color: transparent;color: blue;border: none;">
            </form>
        <?php }
    
    }?>     
 </p>

 <table class="table">
 <tr>
     <th>Recipe Name</th>
     <th>Duration</th>
     <th>Difficulty</th>
     <th>&nbsp;</th>
 </tr>
 <?php if(@$_POST['showMyOwnRecipes']){
            foreach ($recipes as $recipe) : 
               if(strcmp($_SESSION['user'],$recipe->createUserID) == 0) {
     ?>
 <tr>
     <td><?php echo $this->escapeHtml($recipe->recipeName);?></td>
     <td><?php echo $this->escapeHtml($recipe->duration." minutes");?></td>
     <td><?php echo $this->escapeHtml($difficulties[$recipe->recipeID]);?></td>
     <td>
         <a href="<?php echo $this->url('recipe',
             array('action'=>'detailedView', 'recipeID' => $recipe->recipeID));?>">View</a>
         <!--CVL there should be some space -->
    <?php
            if($_SESSION['user'] != "") {                            
            echo "&nbsp <a href=".$this->url('recipe', array('action'=>'addToList', 'recipeID' => $recipe->recipeID)).">Favorite this recipe</a>";                                  
            ?> 
            &nbsp&nbsp<a href="<?php echo $this->url('recipe',
            array('action'=>'edit', 'recipeID' => $recipe->recipeID));?>">Edit</a>              
            &nbsp&nbsp<a href="<?php echo $this->url('recipe',
            array('action'=>'delete', 'recipeID' => $recipe->recipeID));?>">Delete</a>
        <?php }?>  
     </td>
 </tr>
         <?php }
        endforeach;?> 
     <?php
      }else{
          foreach ($recipes as $recipe) : 
     ?>
 <tr>
     <td><?php echo $this->escapeHtml($recipe->recipeName);?></td>
     <td><?php echo $this->escapeHtml($recipe->duration." minutes");?></td>
     <td><?php echo $this->escapeHtml($difficulties[$recipe->recipeID]);?></td>
     <td>
         <a href="<?php echo $this->url('recipe',
             array('action'=>'detailedView', 'recipeID' => $recipe->recipeID));?>">View</a>
         <!--CVL there should be some space -->
         <?php
            if($_SESSION['user'] != "") {                 
            echo "&nbsp&nbsp<a href=".$this->url('recipe', array('action'=>'addToList', 'recipeID' => $recipe->recipeID)).">Favorite this recipe</a>";                        
            
         ?>
         <?php if(strcmp($_SESSION['user'],$recipe->createUserID) == 0) { ?>
         &nbsp&nbsp<a href="<?php echo $this->url('recipe',
             array('action'=>'edit', 'recipeID' => $recipe->recipeID));?>">Edit</a>
         &nbsp&nbsp<a href="<?php echo $this->url('recipe',
             array('action'=>'delete', 'recipeID' => $recipe->recipeID));?>">Delete</a>
 <?php }
            }?>
     </td>
 </tr>
     <?php endforeach; 
     }?>
 </table>