<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Latest recipes';
 $this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <?php
     if(strcmp($_SESSION['user'],"") != 0) {
         echo "<a href=".$this->url('recipe', array('action'=>'createRecipe')).">Add new recipe</a>";
         //CVL3 ins
         //CVL3 TODO space between links
         echo "<a href=".$this->url('list', array('action'=>'viewList')).">View favorite recipes</a>";
     }
     ?>     
 </p>

 <table class="table">
 <tr>
     <th>Recipe Name</th>
     <th>Duration</th>
     <th>Difficulty</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($recipes as $recipe) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($recipe->recipeName);?></td>
     <td><?php echo $this->escapeHtml($recipe->duration." minutes");?></td>
     <td><?php echo $this->escapeHtml($difficulties[$recipe->recipeID]);?></td>
     <td>
         <a href="<?php echo $this->url('recipe',
             array('action'=>'detailedView', 'recipeID' => $recipe->recipeID));?>">View</a>
         <a href="<?php echo $this->url('recipe',
             array('action'=>'edit', 'recipeID' => $recipe->recipeID));?>">Edit</a>
         <a href="<?php echo $this->url('recipe',
             array('action'=>'delete', 'recipeID' => $recipe->recipeID));?>">Delete</a>

         <!--CVL there should be some space -->
         <?php
            if($_SESSION['user'] != "") {                 
            echo "<a href=".$this->url('recipe', array('action'=>'addToList', 'recipeID' => $recipe->recipeID)).">Favorite recipe</a>";                        
            }
         ?>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>