<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/** //CVL5
 * Description of search-term 
 */

    $title = 'Search for recipe';
    $this->headTitle($title);
    ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <br>
    <?php
    $form->setAttribute('action', $this->url('search', array('action' => 'search')
            ));    
    $form->prepare();

    echo "<br>";
    echo $this->form()->openTag($form);    
    echo $this->formRow($form->get('searchTerm'));
    echo "<br>";
    echo $this->formSubmit($form->get('submit'));    
    echo $this->form()->closeTag();
