<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 * Description of list with listdetails 
 */
//assumption only logged-in user can use this feature
if(strcmp($_SESSION['user'], "") != 0) { 
 $user = $_SESSION['user']; 
 $title = 'Favorite Recipes';
 $this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
  
 
 <table class="table">
 <tr>
     <th>Recipe Name</th>
     <th>Duration</th>
     <th>Difficulty</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($recipes as $recipe) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($recipe->recipeName);?></td>
     <td><?php echo $this->escapeHtml($recipe->duration." minutes");?></td>
     <td><?php echo $this->escapeHtml($difficulties[$recipe->recipeID]);?></td>
     <td>         
         <a href="<?php echo $this->url('list',
             array('action'=>'removeFromList', 'recipeID' => $recipe->recipeID));?>">Remove from list </a>    
            &nbsp&nbsp<a href="<?php echo $this->url('recipe',
                array('action'=>'detailedView', 'recipeID' => $recipe->recipeID));?>">View</a>
            <?php
               if($_SESSION['user'] != "") {                                
              //only own recipes can be edited / deleted
              if(strcmp($_SESSION['user'],$recipe->createUserID) == 0) { ?>
                &nbsp&nbsp<a href="<?php echo $this->url('recipe',
                array('action'=>'edit', 'recipeID' => $recipe->recipeID));?>">Edit</a>
                &nbsp&nbsp<a href="<?php echo $this->url('recipe',
                array('action'=>'delete', 'recipeID' => $recipe->recipeID));?>">Delete</a>
               <?php } ?>                              
           <?php }?>  
        </td>
 </tr>
 <?php endforeach; ?>
 </table>
<?php  } ?>