<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 * Description of list with listdetails
 *
 * CVL3
 * 
 */
//TODO use index.phtml? right now list propteries are not relevant anyway, title need to be diff
//loggin is prerequisite to access this page
if(strcmp($_SESSION['user'], "") != 0) {
 //CVL3 - should the displayname be shwon? -> @Daly how to access that
 $user = $_SESSION['user']; 
 $title = 'Favorite Recipes of '.$user;
 $this->headTitle($title);

 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
  
 
 <!--CVL3 - listinfos missing, not relevant because default values-->
 <!--p>
 <!--?php echo $this->escapeHtml("Listname: ".$list->listName);?-->
 <!--?php echo $this->escapeHtml("Listdescription: ".$list->listDescription);?-->
 <!--/p-->
 
 <table class="table">
 <tr>
     <th>Recipe Name</th>
     <th>Duration</th>
     <th>Difficulty</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($recipes as $recipe) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($recipe->recipeName);?></td>
     <td><?php echo $this->escapeHtml($recipe->duration." minutes");?></td>
     <td><?php echo $this->escapeHtml($difficulties[$recipe->recipeID]);?></td>
     <td>
         <!--CVL4-->
         <a href="<?php echo $this->url('list',
             array('action'=>'removeFromList', 'recipeID' => $recipe->recipeID));?>">remove from list </a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
<?php  } ?>