<?php echo $this->doctype();

if(@$_POST['logout']){ 
    logout();
    //AJ: this forces the page to refresh instantly, is probably not a very good solution
    header( "refresh:0;" );
}
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('MYLE')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('MYLE') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <!-- AJ: comment this part so that we only have one link to the homepage
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                    -->
           <?php
                
                $u = getLoginDisplayName();

                if($u==""): ?>
                    <span style="position: absolute;right: 30px;top: 15px;">
                         <a href="<?php echo $this->url('login', array('action'=>'add'));?>">Login</a>
                    </span>      
           <?php else:  ?>
                    <span style="position: absolute;right: 30px;top: 15px; color: white;">
                       
                        <form action="<?php echo $this->url('recipe', array('action'=>'index'));?>" method="POST">
                             Hi <?php echo $u; ?> &nbsp;&nbsp;<input type="submit" name="logout" Value="Logout" style="background-color: transparent;color: #00BFFF;border: none;">
                        </form>
                    </span>
                   
           <?php endif; ?>
                    
                    <!-- AJ: for navigation-->
                    <div class="collapse navbar-collapse">
                        <?php
                        // <-- Update this !!
                        echo $this->navigation('navigation')
                                ->menu()
                                ->setMinDepth(0)
                                ->setMaxDepth(0)
                                ->setUlClass('nav navbar-nav');
                        ?>
                    </div>
                  
                    
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <!-- AJ: navigation breadcrumbs -->
            <?php
            echo $this->navigation('navigation') // <-- Update this!!
                    ->breadcrumbs()
                    ->setMinDepth(1)
                    ->setPartial('partial/breadcrumb.phtml');
            ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
