<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Making Your Life Easier'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php 
       echo 'Cooking is exhausting, but thinking of what to cook and what ingredients to buy is even more exhausting!';
       ?>
       <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">
    <p><a class="btn btn-success btn-lg" href="<?php echo $this->url('recipe', array('action'=>'index'));?>">Go to all the recipes >></a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Our goal') ?></h3>
            </div>
            <div class="panel-body" style="height: 120px">
                <p><?php echo sprintf($this->translate('Making the whole process of cooking easier.'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
            </div>
        </div>
    </div>
       
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Project idea') ?></h3>
            </div>
            <div class="panel-body" style="height: 120px">
                <p><?php echo 'Finding new recipes, creating shopping lists, favoriting interesting recipes for later use and create your own recipes.'; ?></p>
       </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Navigation') ?></h3>
            </div>
            <div class="panel-body" style="height: 120px">
                <p><a href="<?php echo $this->url('recipe', array('action'=>'index'));?>">Recipe</a> >> view all the recipes, Search for recipes, Add new recipe  or View favorite recipes.  
                <p><a href="<?php echo $this->url('list', array('action'=>'viewList'));?>">Favorites List</a> >> view your favorite recipes.
                <p><a href="<?php echo $this->url('login', array('action'=>'add'));?>">Login</a> >> Login or Create new account.
        </div>
        </div>
    </div>
 
</div>
